name: Publish preview

on:
  pull_request:
  push:
    branches:
      - main
      - next

jobs:
  release-preview:
    name: Publish preview releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm build

      - name: Publish preview releases
        run: pnpm pkg-pr-new publish